# Generated by Django 3.2.7 on 2021-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='94TBJD1LelFjhWXZZ69krPvvAkrK8R1cowcZz70dUCCgK2M5WWgIVAyLd0lC9kTMv9c', max_length=100),
        ),
    ]
