# Generated by Django 3.2.7 on 2021-11-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='country',
            new_name='currency',
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='fbAi7GpXk7H880oHIgMe2mGpYbxmqFCEHqnUsapC01nK7bQO_lGCQVXHMSyNmsTmqDI', max_length=100),
        ),
    ]
