# Generated by Django 3.2.7 on 2021-12-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20211128_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='BGWZDeFuo1LHv03jxxzb9qK6Vkotgj-yq_fhBonff5uHjGIDkR3M-kdiYjHBBFPj3Rg', max_length=100),
        ),
    ]
