# Generated by Django 3.2.7 on 2021-12-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='WNu1TMHq5rahWwCHZ74sSzoUgBSJs7PHqGFMtCbK_CyDhAzLQA9a3-TarUIAWFQPfp0', max_length=100),
        ),
    ]
